uq_method:
  _target_: lightning_uq_box.uq_methods.DeterministicClassification
  model:
    _target_: lenet.LeNet
  optimizer:
    _target_: torch.optim.Adam
    _partial_: True
    lr: 0.001
  loss_fn:
    _target_: torch.nn.CrossEntropyLoss