uq_method:
  _target_: lightning_uq_box.uq_methods.SNGPClassification
  feature_extractor:
    _target_: lenet.LeNet
    num_classes: 16 # feature space dimension
  num_targets: 10 # mnist has 10 classes
  loss_fn:
    _target_: torch.nn.CrossEntropyLoss
  input_size: 28
  optimizer:
    _target_: torch.optim.Adam
    _partial_: True
    lr: 0.0001