experiment:
  experiment_name: "cyclone"
  exp_dir: "/my_experiment_directory/"
wandb:
  project: digital_typhoon
  entity: my_entity
  mode: offline

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  min_epochs: 20
  max_epochs: 30
  log_every_n_steps: 50
  enable_progress_bar: True

imagenet_ckpt: /p/project/data/resnet18.ckpt
# imagenet_ckpt: /p/project/data/efficientnet_b0.ckpt