experiment:
  experiment_name: "poverty"
  exp_dir: "/p/project/hai_uqmethodbox/experiment_output/wilds_poverty"
wandb:
  project: poverty
  entity: nilsleh
  mode: offline

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  max_epochs: 100
  log_every_n_steps: 50
  enable_progress_bar: True