experiment:
  experiment_name: "skippd"
  exp_dir: "uq-box-experiments/my_experiments"
wandb:
  project: skippd
  entity: nilsleh
  mode: offline

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  min_epochs: 20
  max_epochs: 30
  log_every_n_steps: 50
  enable_progress_bar: True
