uq_method:
  _target_: lightning_uq_box.uq_methods.SNGPRegression
  feature_extractor:
    _target_: timm.create_model
    model_name: resnet18
    num_classes: 32 # feature space dimension
    drop_rate: 0.1
  num_targets: 38
  loss_fn:
    _target_: torch.nn.CrossEntropyLoss
  input_size: 224