uq_method:
  _target_: lightning_uq_box.uq_methods.BNN_VI_ELBO_Classification
  model:
    _target_: resnet.ResNet20
  criterion:
    _target_: torch.nn.CrossEntropyLoss
  num_mc_samples_train: 2
  num_mc_samples_test: 10
  prior_mu: 0.0
  prior_sigma: 1.0
  posterior_mu_init: 0.0
  posterior_rho_init: -3.0
  beta: 0
  bayesian_layer_type: "flipout"
  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 0.003