uq_method:
  _target_: lightning_uq_box.uq_methods.DKLClassification
  feature_extractor:
    _target_: resnet.ResNet20
    dropout_p: 0.1
    classes: 32 # num latent features
  n_inducing_points: 300
  gp_kernel: "RBF"
  num_classes: 10 # cifar10 has 10 classes
  optimizer:
    _target_: torch.optim.Adam # can change optimizers here easily
    _partial_: true
    lr: 0.0001
  # lr_scheduler:
  #   _target_: scheduler.wilson_scheduler
  #   _partial_: True
  #   pretrain_epochs: 300 # needs to match with trainer
  #   lr_init: 0.0001