uq_method:
  _target_: lightning_uq_box.uq_methods.MCDropoutClassification
  model:
    _target_: resnet.ResNet20
    dropout_p: 0.1
  loss_fn: 
    _target_: torch.nn.CrossEntropyLoss
  optimizer:
    _target_: torch.optim.SGD
    _partial_: True
    lr: 0.05
    momentum: 0.9
    nesterov: True
  lr_scheduler:
    _target_: scheduler.wilson_scheduler
    _partial_: True
    pretrain_epochs: 300 # needs to match with trainer
    lr_init: 0.05
  num_mc_samples: 50