uq_method:
  _target_: lightning_uq_box.uq_methods.SNGPClassification
  feature_extractor:
    _target_: resnet.ResNet20
    # dropout_p: 0.1
    classes: 128 # feature space dimension
    norm: batch_static
  num_targets: 10 # cifar10 has 10 classes
  loss_fn:
    _target_: torch.nn.CrossEntropyLoss
  input_size: 32
  normalize_gp_features: False
  coeff: 6.0
  optimizer:
    _target_: torch.optim.SGD
    _partial_: True
    lr: 0.05
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0003
  lr_scheduler:
    _target_: scheduler.wilson_scheduler
    _partial_: True
    pretrain_epochs: 300 # needs to match with trainer
    lr_init: 0.05
  mean_field_factor: 20

# uq_method:
#   _target_: lightning_uq_box.uq_methods.SNGPClassification
#   feature_extractor:
#     _target_: resnet.ResNet20
#     dropout_p: 0.1
#     classes: 32 # feature space dimension
#   num_targets: 10 # cifar10 has 10 classes
#   loss_fn:
#     _target_: torch.nn.CrossEntropyLoss
#   input_size: 32
#   normalize_gp_features: False
#   coeff: 6.0
#   optimizer:
#     _target_: torch.optim.SGD
#     _partial_: True
#     lr: 0.05
#     momentum: 0.9
#     nesterov: True
#     weight_decay: 0.0003
#   lr_scheduler:
#     _target_: scheduler.wilson_scheduler
#     _partial_: True
#     pretrain_epochs: 300 # needs to match with trainer
#     lr_init: 0.05
#   mean_field_factor: 20
