experiment:
  experiment_name: "cifar10"
  exp_dir: "/p/project/hai_uqmethodbox/experiment_output/cifar10-sngp-final"
wandb:
  project: cifar10
  entity: uq-regression
  mode: offline

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  min_epochs: 300
  max_epochs: 350
  log_every_n_steps: 50
  enable_progress_bar: True
  limit_val_batches: 0 # no validation set in cifar10
  # overfit_batches: 10